package compiler;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class Main {
    public static void main(String[] args) throws Exception {
        String input = Files.readString(Path.of("src/main/resources/sample.test"));

        Lexer lexer = new Lexer(input);
        List<Token> tokens = lexer.tokenize();

        Parser parser = new Parser(tokens);
        AST.Program program = parser.parseProgram();

        BytecodeEmitter emitter = new BytecodeEmitter();
        List<String> bytecode = emitter.emit(program);

        System.out.println("Generated Bytecode:");
        bytecode.forEach(System.out::println);

        System.out.println("\nProgram Output:");
        VM vm = new VM(bytecode);
        vm.run();
    }
}
